baseURL = 'https://chuyro.github.io/Test-HUGO-WEBPAGE/'
languageCode = 'es-es'
title = 'Pagina Personal'
theme = 'ananke'

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0
	[[menu.main]]
	identifier = "about"
	name = "About"
	title = "About"
	url = "/about/"
	weight = 0
